In [1]:
import numpy as np

In [2]:
arr_2t032=np.arange(2,34,2).reshape(4,4)
mean=arr_2t032.mean()
std=arr_2t032.std()
print(mean)
print(std)

17.0
9.219544457292887


In [3]:
lower =mean-0.5*std
upper=mean+0.5*std

In [4]:
result=arr_2t032[(arr_2t032>=lower)&(arr_2t032<=upper)]
print(result)

[14 16 18 20]


In [6]:
print("arr\n",arr_2t032)
print("mean:",mean)
print('std:',std)

arr
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
mean: 17.0
std: 9.219544457292887
